// Mock data for Delhi districts and wards

import type { District, Ward, WaterLoggingReport, Alert, PumpDeployment, User } from "./types"

// Delhi Districts
export const districts: District[] = [
  { id: "nd", name: "New Delhi" },
  { id: "cd", name: "Central Delhi" },
  { id: "nod", name: "North Delhi" },
  { id: "sd", name: "South Delhi" },
  { id: "ed", name: "East Delhi" },
  { id: "wd", name: "West Delhi" },
  { id: "ned", name: "North East Delhi" },
  { id: "sed", name: "South East Delhi" },
  { id: "swd", name: "South West Delhi" },
  { id: "sh", name: "Shahdara" },
  { id: "nwd", name: "North West Delhi" },
]

// Generate wards for each district (total ~250 wards)
const generateWardsForDistrict = (districtId: string, districtName: string, count: number): Ward[] => {
  const wards: Ward[] = []
  for (let i = 1; i <= count; i++) {
    const riskScore = Math.floor(Math.random() * 100)
    wards.push({
      id: `${districtId}-w${i}`,
      name: `${districtName} Ward ${i}`,
      districtId,
      riskScore,
      riskLevel: riskScore >= 70 ? "HIGH" : riskScore >= 40 ? "MEDIUM" : "LOW",
    })
  }
  return wards
}

export const wards: Ward[] = [
 // South Delhi (sd)
{
  id: "sd-w1",
  name: "Nizamuddin",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w2",
  name: "Lajpat Nagar",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w3",
  name: "Bhogal",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w4",
  name: "Kasturba Nagar",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w5",
  name: "Kotla Mubarakpur",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w6",
  name: "Andrews Ganj",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w7",
  name: "Amar Colony",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w8",
  name: "Malviya Nagar",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w9",
  name: "Village Hauz Rani",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w10",
  name: "Safdarjung Enclave",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w11",
  name: "Hauz Khas",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w12",
  name: "R.K. Puram",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w13",
  name: "Lado Sarai",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w14",
  name: "Mehrauli",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w15",
  name: "Said-ul-Ajaib",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w16",
  name: "Chhatarpur",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w17",
  name: "Aya Nagar",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w18",
  name: "Bhatti",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w19",
  name: "Sangam Vihar",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w20",
  name: "Devli",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w21",
  name: "Tigri",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w22",
  name: "Dakshin Puri Ext.",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w23",
  name: "Khanpur",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w24",
  name: "Ambedkar Nagar",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w25",
  name: "Madangir",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w26",
  name: "Pushp Vihar",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w27",
  name: "Tuglakabad Ext.",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w28",
  name: "Sangam Vihar (West)",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w29",
  name: "Sangam Vihar (Central)",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w30",
  name: "Sangam Vihar (East)",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w31",
  name: "Chirag Delhi",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w32",
  name: "Chittaranjan Park",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w33",
  name: "Shahpur Jat",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w34",
  name: "Greater Kailash-I",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w35",
  name: "Sri Niwas Puri",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sd-w36",
  name: "East of Kailash",
  districtId: "sd",
  riskScore: 0,
  riskLevel: "LOW",
},
// Central Delhi (cd)
{
  id: "cd-w1",
  name: "Jama Masjid",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w2",
  name: "Minto Road",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w3",
  name: "Kuccha Pandit",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w4",
  name: "Sita Ram Bazar",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w5",
  name: "Turkman Gate",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w6",
  name: "Ballimaran",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w7",
  name: "Ram Nagar",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w8",
  name: "Pahar Ganj",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w9",
  name: "Karol Bagh",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w10",
  name: "Dev Nagar",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w11",
  name: "Rajinder Nagar",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "cd-w12",
  name: "Darya Ganj",
  districtId: "cd",
  riskScore: 0,
  riskLevel: "LOW",
},
// East Delhi (ed)
{
  id: "ed-w1",
  name: "Mayur Vihar Phase-I",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w2",
  name: "Dallu Pura",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w3",
  name: "Trilok Puri",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w4",
  name: "New Ashok Nagar",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w5",
  name: "Kalyan Puri",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w6",
  name: "Khichri Pur",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w7",
  name: "Kondli",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w8",
  name: "Gharoli",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w9",
  name: "Vinod Nagar",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w10",
  name: "Mandavali",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w11",
  name: "Mayur Vihar Phase-II",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w12",
  name: "Patparganj",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ed-w13",
  name: "Kishan Kunj",
  districtId: "ed",
  riskScore: 0,
  riskLevel: "LOW",
},
// New Delhi (nd)
{
  id: "nd-w1",
  name: "Connaught Place",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nd-w2",
  name: "Gole Market",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nd-w3",
  name: "Karol Bagh (New Delhi area)",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nd-w4",
  name: "Paharganj",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nd-w5",
  name: "Delhi Cantt",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nd-w6",
  name: "R.K. Ashram Marg",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nd-w7",
  name: "Minto Road",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nd-w8",
  name: "Bengali Market",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nd-w9",
  name: "India Gate",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nd-w10",
  name: "Chanakyapuri",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nd-w11",
  name: "Parliament Street",
  districtId: "nd",
  riskScore: 0,
  riskLevel: "LOW",
},
// North Delhi (nod)
{
  id: "nod-w1",
  name: "Mukandpur",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w2",
  name: "Burari",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w3",
  name: "Jharoda",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w4",
  name: "Malka Ganj",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w5",
  name: "Timarpur",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w6",
  name: "Mukherji Nagar",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w7",
  name: "Kamla Nagar",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w8",
  name: "Shastri Nagar",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w9",
  name: "Inderlok Colony",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w10",
  name: "Kishan Ganj",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w11",
  name: "Deputy Ganj",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w12",
  name: "Kashmere Gate",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w13",
  name: "Majnoo Ka Tilla",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w14",
  name: "Chandni Chawk",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w15",
  name: "Eidgah Road",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w16",
  name: "Ram Nagar",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w17",
  name: "Kasabpura",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w18",
  name: "Model Basti",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nod-w19",
  name: "Karol Bagh",
  districtId: "nod",
  riskScore: 0,
  riskLevel: "LOW",
},
// North East Delhi (ned)
{
  id: "ned-w1",
  name: "Welcome Colony",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w2",
  name: "Seelampur",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w3",
  name: "Gautam Puri",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w4",
  name: "Chauhan Banger",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w5",
  name: "Maujpur",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w6",
  name: "Brahampuri",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w7",
  name: "Bhajanpura",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w8",
  name: "Ghonda",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w9",
  name: "Yamuna Vihar",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w10",
  name: "Subhash Mohalla",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w11",
  name: "Kabir Nagar",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w12",
  name: "Gorakh Park",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w13",
  name: "Kardam Puri",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w14",
  name: "Harsh Vihar",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w15",
  name: "Saboli",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w16",
  name: "Gokal Puri",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w17",
  name: "Joharipur",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w18",
  name: "Karawal Nagar East",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w19",
  name: "Dayalpur",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w20",
  name: "Mustafabad",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w21",
  name: "Nehru Vihar",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w22",
  name: "Brij Puri",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w23",
  name: "Shri Ram Colony",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w24",
  name: "Sadatpur",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w25",
  name: "Karawal Nagar West",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w26",
  name: "Sonia Vihar",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "ned-w27",
  name: "Sabapur",
  districtId: "ned",
  riskScore: 0,
  riskLevel: "LOW",
},
// North West Delhi (nwd)
{
  id: "nwd-w1",
  name: "Narela",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w2",
  name: "Bankner",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w3",
  name: "Alipur",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w4",
  name: "Bakhtawarpur",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w5",
  name: "Bhalaswa Jahangirpuri",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w6",
  name: "Mukherji Nagar",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w7",
  name: "G.T.B. Nagar",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w8",
  name: "Dhirpur",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w9",
  name: "Adarsh Nagar",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w10",
  name: "Sarai Pepal Thalla",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w11",
  name: "Jahangirpuri - I",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w12",
  name: "Samaypur Badli",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "nwd-w13",
  name: "Libaspur",
  districtId: "nwd",
  riskScore: 0,
  riskLevel: "LOW",
},
// Shahdara (sh)
{
  id: "sh-w1",
  name: "Shahdara",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w2",
  name: "Jhilmil",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w3",
  name: "Dilshad Colony",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w4",
  name: "Sundar Nagri",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w5",
  name: "Dilshad Garden",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w6",
  name: "Nand Nagri",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w7",
  name: "Ashok Nagar",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w8",
  name: "Ram Nagar East",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w9",
  name: "Rohtash Nagar",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w10",
  name: "Anand Vihar",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w11",
  name: "Jagat Puri",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sh-w12",
  name: "Geeta Colony",
  districtId: "sh",
  riskScore: 0,
  riskLevel: "LOW",
},
// South East Delhi (sed)
{
  id: "sed-w1",
  name: "Kalkaji",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w2",
  name: "Govind Puri",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w3",
  name: "Harkesh Nagar",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w4",
  name: "Tughlakabad",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w5",
  name: "Tughlakabad Extension",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w6",
  name: "Pul Pehladpur",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w7",
  name: "Badarpur",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w8",
  name: "Molarband",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w9",
  name: "Meethapur",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w10",
  name: "Jaitpur",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w11",
  name: "Hari Nagar Extension",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w12",
  name: "Madanpur Khadar East",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w13",
  name: "Madanpur Khadar West",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w14",
  name: "Sarita Vihar",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w15",
  name: "Abul Fazal Enclave",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "sed-w16",
  name: "Zakir Nagar",
  districtId: "sed",
  riskScore: 0,
  riskLevel: "LOW",
},
// West Delhi (wd)
{
  id: "wd-w1",
  name: "Punjabi Bagh",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w2",
  name: "Madipur",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w3",
  name: "Raghubir Nagar",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w4",
  name: "Vishnu Garden",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w5",
  name: "Rajouri Garden",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w6",
  name: "Chaukhandi Nagar",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w7",
  name: "Subhash Nagar",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w8",
  name: "Hari Nagar",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w9",
  name: "Fateh Nagar",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w10",
  name: "Tilak Nagar",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w11",
  name: "Khyala",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w12",
  name: "Keshopur",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w13",
  name: "Janak Puri South",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w14",
  name: "Mahaveer Enclave",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w15",
  name: "Janak Puri West",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w16",
  name: "Vikas Puri",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w17",
  name: "Hastsal",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w18",
  name: "Vikas Nagar",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w19",
  name: "Kunwar Singh Nagar",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w20",
  name: "Baprola",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w21",
  name: "Sainik Enclave",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w22",
  name: "Mohan Garden",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w23",
  name: "Nawada",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w24",
  name: "Uttam Nagar",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "wd-w25",
  name: "Binda Pur",
  districtId: "wd",
  riskScore: 0,
  riskLevel: "LOW",
},
// South West Delhi (swd)
{
  id: "swd-w1",
  name: "Dabri",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w2",
  name: "Sagarpur",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w3",
  name: "Manglapuri",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w4",
  name: "Dwarka-B",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w5",
  name: "Dwarka-A",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w6",
  name: "Matiala",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w7",
  name: "Kakrola",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w8",
  name: "Nangli Sakrawati",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w9",
  name: "Chhawla",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w10",
  name: "Isapur",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w11",
  name: "Najafgarh",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w12",
  name: "Dichaon Kalan",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w13",
  name: "Roshan Pura",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w14",
  name: "Dwarka-C",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w15",
  name: "Bijwasan",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w16",
  name: "Kapashera",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w17",
  name: "Mahipalpur",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w18",
  name: "Raj Nagar",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w19",
  name: "Palam",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w20",
  name: "Madhu Vihar",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w21",
  name: "Mahavir Enclave",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},
{
  id: "swd-w22",
  name: "Sadh Nagar",
  districtId: "swd",
  riskScore: 0,
  riskLevel: "LOW",
},

];

// Mock users
export const users: User[] = [
  { id: "u1", name: "Rahul Kumar", email: "rahul@example.com", role: "CITIZEN", districtId: "nd", wardId: "nd-w1" },
  { id: "u2", name: "Priya Sharma", email: "priya@example.com", role: "COMMUTER", districtId: "sd", wardId: "sd-w5" },
  { id: "u3", name: "Amit Singh", email: "amit@example.com", role: "OFFICIAL", districtId: "cd" },
  { id: "u4", name: "Anjali Gupta", email: "anjali@example.com", role: "ADMIN" },
]

// Mock water-logging reports
export const reports: WaterLoggingReport[] = [
  {
    id: "r1",
    userId: "u1",
    userName: "Rahul Kumar",
    districtId: "nd",
    districtName: "New Delhi",
    wardId: "nd-w1",
    wardName: "ND Ward 1",
    severity: "HIGH",
    description: "Severe water-logging near Connaught Place",
    location: "Connaught Place Metro Station",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: "NEW",
  },
  {
    id: "r2",
    userId: "u2",
    userName: "Priya Sharma",
    districtId: "sd",
    districtName: "South Delhi",
    wardId: "sd-w5",
    wardName: "SD Ward 5",
    severity: "MEDIUM",
    description: "Water accumulation on main road",
    location: "Hauz Khas Main Road",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: "IN_PROGRESS",
  },
  {
    id: "r3",
    userId: "u1",
    userName: "Rahul Kumar",
    districtId: "cd",
    districtName: "Central Delhi",
    wardId: "cd-w3",
    wardName: "CD Ward 3",
    severity: "LOW",
    description: "Minor water-logging near park",
    location: "Karol Bagh Park",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: "RESOLVED",
  },
]

// Mock alerts
export const alerts: Alert[] = [
  {
    id: "a1",
    districtId: "nd",
    districtName: "New Delhi",
    wardId: "nd-w1",
    wardName: "ND Ward 1",
    title: "High Risk Alert",
    message: "Heavy rainfall expected. Water-logging likely in low-lying areas.",
    severity: "HIGH",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "a2",
    districtId: "sd",
    districtName: "South Delhi",
    title: "Moderate Risk",
    message: "Multiple water-logging incidents reported. Avoid main roads.",
    severity: "MEDIUM",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
]

// Mock pump deployments
export const pumpDeployments: PumpDeployment[] = [
  {
    id: "p1",
    wardId: "nd-w1",
    wardName: "ND Ward 1",
    districtId: "nd",
    districtName: "New Delhi",
    pumpCount: 5,
    status: "DEPLOYED",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "p2",
    wardId: "sd-w5",
    wardName: "SD Ward 5",
    districtId: "sd",
    districtName: "South Delhi",
    pumpCount: 3,
    status: "IN_TRANSIT",
    lastUpdated: new Date().toISOString(),
  },
]
