export type WardConfig = {
  id: string
  name: string
  district: string
  districtId: string
  lat: number
  lon: number
}

export const WARDS: WardConfig[] = [
  // South Delhi wards with approximate centroids

  { // Malviya Nagar[web:181][web:184]
    id: "SOUTH_MALVIYA_NAGAR",
    name: "Malviya Nagar",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",  
    lat: 28.5342,
    lon: 77.2094,
  },
  { // Aya Nagar[web:182][web:185]
    id: "SOUTH_AYA_NAGAR",
    name: "Aya Nagar",
    district: "South Delhi",
        districtId: "SOUTH_DELHI",  
    lat: 28.4765,
    lon: 77.1329,
  },
  { // Mehrauli[web:183][web:189]
    id: "SOUTH_MEHRAULI",
    name: "Mehrauli",
    district: "South Delhi",
        districtId: "SOUTH_DELHI",  

    lat: 28.5143,
    lon: 77.1796,
  },

  { // Nizamuddin (near Hazrat Nizamuddin area)[web:180][web:181]
    id: "SOUTH_NIZAMUDDIN",
    name: "Nizamuddin",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5934,
    lon: 77.2495,
  },
  { // Lajpat Nagar[web:181][web:184]
    id: "SOUTH_LAJPAT_NAGAR",
    name: "Lajpat Nagar",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5677,
    lon: 77.2433,
  },
  { // Bhogal (Jangpura/Bhogal area – approx.)[web:180][web:181]
    id: "SOUTH_BHOGAL",
    name: "Bhogal",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5820,
    lon: 77.2450,
  },
{ // Kasturba Nagar (near Siri Fort)[web:181][web:184]
    id: "SOUTH_KASTURBA_NAGAR",
    name: "Kasturba Nagar",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5560,
    lon: 77.2220,
  },
  { // Kotla Mubarakpur (near South Ex)[web:181]
    id: "SOUTH_KOTLA_MUBARAKPUR",
    name: "Kotla Mubarakpur",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5675,
    lon: 77.2195,
  },
  { // Andrews Ganj (near Lajpat Nagar / Defence Colony)[web:181]
    id: "SOUTH_ANDREWS_GANJ",
    name: "Andrews Ganj",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5645,
    lon: 77.2290,
  },
{ // Amar Colony (near Lajpat Nagar)[web:181]
    id: "SOUTH_AMAR_COLONY",
    name: "Amar Colony",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5685,
    lon: 77.2500,
  },
  
  { // Village Hauz Rani (near Malviya Nagar)[web:181][web:179]
    id: "SOUTH_VILLAGE_HAUZ_RANI",
    name: "Village Hauz Rani",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5348,
    lon: 77.2108,
  },
  { // Safdarjung Enclave[web:181]
    id: "SOUTH_SAFDARJUNG_ENCLAVE",
    name: "Safdarjung Enclave",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5595,
    lon: 77.1996,
  },

  { // Hauz Khas[web:181]
    id: "SOUTH_HAUZ_KHAS",
    name: "Hauz Khas",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5494,
    lon: 77.2001,
  },
  { // R.K. Puram[web:181]
    id: "SOUTH_RK_PURAM",
    name: "R.K. Puram",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5634,
    lon: 77.1835,
  },
  { // Lado Sarai (near Saket/Mehrauli)[web:183][web:189]
    id: "SOUTH_LADO_SARAI",
    name: "Lado Sarai",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5252,
    lon: 77.2007,
  },

  { // Said-ul-Ajaib (near Saket / Garden of Five Senses)[web:195][web:204]
    id: "SOUTH_SAID_UL_AJAIB",
    name: "Said-ul-Ajaib",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5150,
    lon: 77.2020,
  },
  { // Chhatarpur (using Chattarpur Enclave centroid)[web:201][web:205]
    id: "SOUTH_CHHATARPUR",
    name: "Chhatarpur",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5010,
    lon: 77.1880,
  },
  { // Bhatti (Bhatti Mines / Bhatti Kalan area)[web:198][web:202][web:206]
    id: "SOUTH_BHATTI",
    name: "Bhatti",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.4300,
    lon: 77.2260,
  },
  { // Sangam Vihar[web:199][web:203]
    id: "SOUTH_SANGAM_VIHAR",
    name: "Sangam Vihar",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.4985,
    lon: 77.2400,
  },

  { // Devli / Deoli area in South Delhi[web:209][web:215][web:219]
    id: "SOUTH_DEVLI",
    name: "Devli",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.4957,
    lon: 77.2319,
  },
  { // Tigri / Tigri Extension near Sangam Vihar[web:216][web:220]
    id: "SOUTH_TIGRI",
    name: "Tigri",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5072,
    lon: 77.2398,
  },
  { // Dakshin Puri Ext. (Dakshinpuri Extension)[web:213][web:217][web:221]
    id: "SOUTH_DAKSHIN_PURI_EXT",
    name: "Dakshin Puri Ext.",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5208,
    lon: 77.2391,
  },
  { // Khanpur[web:214][web:218]
    id: "SOUTH_KHANPUR",
    name: "Khanpur",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.4723,
    lon: 77.2326,
  },

  { // Ambedkar Nagar (Dr. Ambedkar Nagar, South Delhi)[web:222][web:225][web:234]
    id: "SOUTH_AMBEDKAR_NAGAR",
    name: "Ambedkar Nagar",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5200,
    lon: 77.2350,
  },
  { // Madangir[web:227][web:231][web:235]
    id: "SOUTH_MADANGIR",
    name: "Madangir",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5186,
    lon: 77.2319,
  },
  { // Pushp Vihar[web:228][web:232][web:236]
    id: "SOUTH_PUSHP_VIHAR",
    name: "Pushp Vihar",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5280,
    lon: 77.2150,
  },
  { // Tughlakabad Ext. (Tughlakabad Extension)[web:229][web:233]
    id: "SOUTH_TUGHLAKABAD_EXT",
    name: "Tuglakabad Ext.",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5180,
    lon: 77.2568,
  },
  { // Sangam Vihar (West) – using overall Sangam Vihar centroid near Block L/Devli side[web:199][web:237][web:247]
    id: "SOUTH_SANGAM_VIHAR_WEST",
    name: "Sangam Vihar (West)",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.4984,
    lon: 77.2379,
  },
  { // Sangam Vihar (Central) – same locality, centralised around typical coordinates for the colony[web:199][web:203]
    id: "SOUTH_SANGAM_VIHAR_CENTRAL",
    name: "Sangam Vihar (Central)",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.4989,
    lon: 77.2390,
  },
  { // Sangam Vihar (East) – shifted slightly east from the central ward[web:199][web:203]
    id: "SOUTH_SANGAM_VIHAR_EAST",
    name: "Sangam Vihar (East)",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.4989,
    lon: 77.2435,
  },
  { // Chirag Delhi[web:240][web:248]
    id: "SOUTH_CHIRAG_DELHI",
    name: "Chirag Delhi",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5318,
    lon: 77.2075,
  },

  // …next wards continue…


  { // Chittaranjan Park (C.R. Park)[web:251][web:258]
    id: "SOUTH_CHITTARANJAN_PARK",
    name: "Chittaranjan Park",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5380,
    lon: 77.2516,
  },
  { // Shahpur Jat[web:255][web:259][web:263]
    id: "SOUTH_SHAHPUR_JAT",
    name: "Shahpur Jat",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5492,
    lon: 77.2139,
  },
  { // Greater Kailash-I[web:256][web:260][web:264]
    id: "SOUTH_GREATER_KAILASH_I",
    name: "Greater Kailash-I",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5513,
    lon: 77.2360,
  },
  { // Sri Niwas Puri / Sriniwaspuri area[web:257][web:261]
    id: "SOUTH_SRI_NIWAS_PURI",
    name: "Sri Niwas Puri",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",
    lat: 28.5613,
    lon: 77.2611,
  },


  { // East of Kailash[web:265][web:268][web:269]
    id: "SOUTH_EAST_OF_KAILASH",
    name: "East of Kailash",
    district: "South Delhi",
    districtId: "SOUTH_DELHI",

    lat: 28.5583,
    lon: 77.2530,
  },


  { // Jama Masjid, Central Delhi[web:278][web:279]
    id: "CENTRAL_JAMA_MASJID",
    name: "Jama Masjid",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6587,
    lon: 77.2308,
  },
  { // Minto Road, Central Delhi[web:280][web:286]
    id: "CENTRAL_MINTO_ROAD",
    name: "Minto Road",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6386,
    lon: 77.2447,
  },
  { // Kuccha Pandit – use Old Delhi core approx; can refine when a precise centroid source is available[web:281][web:287]
    id: "CENTRAL_KUCCHA_PANDIT",
    name: "Kuccha Pandit",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6550,
    lon: 77.2300,
  },

  

  { // Sita Ram Bazar (Chandni Chowk, Central Delhi)[web:290][web:291][web:300]
    id: "CENTRAL_SITA_RAM_BAZAR",
    name: "Sita Ram Bazar",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6474,
    lon: 77.2290,
  },
  { // Turkman Gate, Shahjahanabad area[web:294][web:301]
    id: "CENTRAL_TURKMAN_GATE",
    name: "Turkman Gate",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6409,
    lon: 77.23297,
  },
  { // Ballimaran, Old Delhi[web:298]
    id: "CENTRAL_BALLIMARAN",
    name: "Ballimaran",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6558,
    lon: 77.2254,
  },
  { // Ram Nagar, Delhi[web:299]
    id: "CENTRAL_RAM_NAGAR",
    name: "Ram Nagar",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6860,
    lon: 77.2958,
  },

    { // Pahar Ganj / Paharganj, Central Delhi[web:302][web:306][web:310]
    id: "CENTRAL_PAHAR_GANJ",
    name: "Pahar Ganj",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6440,
    lon: 77.2140,
  },
  { // Karol Bagh[web:307][web:311][web:315]
    id: "CENTRAL_KAROL_BAGH",
    name: "Karol Bagh",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6514,
    lon: 77.1907,
  },
  { // Dev Nagar, near Karol Bagh[web:308][web:312][web:316]
    id: "CENTRAL_DEV_NAGAR",
    name: "Dev Nagar",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6550,
    lon: 77.1865,
  },
  { // Rajinder Nagar[web:309][web:313]
    id: "CENTRAL_RAJINDER_NAGAR",
    name: "Rajinder Nagar",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6404,
    lon: 77.1859,
  },
  { // Darya Ganj / Daryaganj[web:318][web:320][web:326]
    id: "CENTRAL_DARYA_GANJ",
    name: "Darya Ganj",
    district: "Central Delhi",
    districtId: "CENTRAL_DELHI",
    lat: 28.6443,
    lon: 77.2420,
  },

   { // Mayur Vihar Phase-I[web:328][web:331][web:335]
    id: "EAST_MAYUR_VIHAR_PHASE_I",
    name: "Mayur Vihar Phase-I",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6035,
    lon: 77.2915,
  },
  { // Dallu Pura / Dallupura[web:332][web:336][web:340]
    id: "EAST_DALLU_PURA",
    name: "Dallu Pura",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6071,
    lon: 77.3188,
  },
  { // Trilok Puri[web:333][web:337][web:341]
    id: "EAST_TRILOK_PURI",
    name: "Trilok Puri",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6079,
    lon: 77.2946,
  },
  { // New Ashok Nagar[web:334][web:338]
    id: "EAST_NEW_ASHOK_NAGAR",
    name: "New Ashok Nagar",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.5900,
    lon: 77.3015,
  },
  { // Kalyan Puri / Kalyanpuri[web:342][web:343][web:354]
    id: "EAST_KALYAN_PURI",
    name: "Kalyan Puri",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6167,
    lon: 77.3189,
  },
  { // Khichri Pur / Khichripur[web:347][web:351][web:355]
    id: "EAST_KHICHRI_PUR",
    name: "Khichri Pur",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6190,
    lon: 77.3195,
  },
  { // Kondli / New Kondli[web:348][web:356]
    id: "EAST_KONDLI",
    name: "Kondli",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6117,
    lon: 77.3261,
  },
  { // Gharoli[web:349][web:352][web:353]
    id: "EAST_GHAROLI",
    name: "Gharoli",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6192,
    lon: 77.3317,
  },
  { // Vinod Nagar (using East/West/Vinod Nagar North centroid in this area)[web:358][web:361][web:365]
    id: "EAST_VINOD_NAGAR",
    name: "Vinod Nagar",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6230,
    lon: 77.2970,
  },
  { // Mandavali / Mandawali Fazalpur[web:367][web:368][web:369]
    id: "EAST_MANDAVALI",
    name: "Mandavali",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6330,
    lon: 77.3000,
  },
  { // Mayur Vihar Phase-II[web:370][web:374]
    id: "EAST_MAYUR_VIHAR_PHASE_II",
    name: "Mayur Vihar Phase-II",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6175,
    lon: 77.3066,
  },
  { // Patparganj[web:371][web:375][web:378]
    id: "EAST_PATPARGANJ",
    name: "Patparganj",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6356,
    lon: 77.3108,
  },
  { // Kishan Kunj – approximate, using nearby East Delhi residential coordinates[web:373][web:376]
    id: "EAST_KISHAN_KUNJ",
    name: "Kishan Kunj",
    district: "East Delhi",
    districtId: "EAST_DELHI",
    lat: 28.6234,
    lon: 77.2905,
  },
  { // Connaught Place (Rajiv Chowk)[web:381][web:383][web:392]
    id: "NEW_DELHI_CONNaught_PLACE",
    name: "Connaught Place",
    districtId: "NEW_DELHI",
    district: "New Delhi",
    lat: 28.6314,
    lon: 77.2167,
  },
  { // Gole Market[web:384][web:387][web:390]
    id: "NEW_DELHI_GOLE_MARKET",
    name: "Gole Market",
    district: "New Delhi",
    districtId: "NEW_DELHI",
    lat: 28.6350,
    lon: 77.2046,
  },
  { // Karol Bagh (New Delhi district context)[web:307][web:311]
    id: "NEW_DELHI_KAROL_BAGH",
    name: "Karol Bagh",
    district: "New Delhi",
    districtId: "NEW_DELHI",
    lat: 28.6514,
    lon: 77.1907,
  },
  { // Paharganj (New Delhi district context)[web:302][web:306]
    id: "NEW_DELHI_PAHARGANJ",
    name: "Paharganj",
    district: "New Delhi",
    districtId: "NEW_DELHI",
    lat: 28.6440,
    lon: 77.2140,
  },
  { // Delhi Cantt / Delhi Cantonment[web:385][web:388][web:391]
    id: "NEW_DELHI_DELHI_CANTT",
    name: "Delhi Cantt",
    district: "New Delhi",
    districtId: "NEW_DELHI",
    lat: 28.5889,
    lon: 77.1324,
  },
  { // R.K. Ashram Marg (metro area)[web:396][web:406]
    id: "NEW_DELHI_RK_ASHRAM_MARG",
    name: "R.K. Ashram Marg",
    district: "New Delhi",
    districtId: "NEW_DELHI",
    lat: 28.6393,
    lon: 77.2085,
  },
  { // Minto Road (New Delhi district side)[web:280][web:286]
    id: "NEW_DELHI_MINTO_ROAD",
    name: "Minto Road",
    district: "New Delhi",
    districtId: "NEW_DELHI",
    lat: 28.6400,
    lon: 77.2320,
  },
  { // Bengali Market[web:399][web:401][web:404]
    id: "NEW_DELHI_BENGALI_MARKET",
    name: "Bengali Market",
    district: "New Delhi",
    districtId: "NEW_DELHI",
    lat: 28.6263,
    lon: 77.2182,
  },
  { // India Gate[web:400][web:402][web:405]
    id: "NEW_DELHI_INDIA_GATE",
    name: "India Gate",
    district: "New Delhi",
    districtId: "NEW_DELHI",
    lat: 28.6129,
    lon: 77.2295,
  },
  { // Chanakyapuri / Chanakya Puri[web:408][web:415][web:417]
    id: "NEW_DELHI_CHANAKYAPURI",
    name: "Chanakyapuri",
    district: "New Delhi",
    districtId: "NEW_DELHI",
    lat: 28.5947,
    lon: 77.1885,
  },
  { // Parliament Street[web:412][web:414][web:418]
    id: "NEW_DELHI_PARLIAMENT_STREET",
    name: "Parliament Street",
    district: "New Delhi",
    districtId: "NEW_DELHI",
    lat: 28.6231,
    lon: 77.2126,
  },
  { // Mukandpur / Mukundpur, North Delhi[web:424][web:426][web:433]
    id: "NORTH_MUKANDPUR",
    name: "Mukandpur",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.7441,
    lon: 77.1450,
  },
  { // Burari[web:430][web:434]
    id: "NORTH_BURARI",
    name: "Burari",
    district: "North Delhi",
   districtId: "NORTH_DELHI",
    lat: 28.7554,
    lon: 77.1941,
  },
  { // Jharoda (Jharoda Majraa Burari side)[web:431][web:435]
    id: "NORTH_JHARODA",
    name: "Jharoda",
    district: "North Delhi",
  districtId: "NORTH_DELHI",
    lat: 28.7608,
    lon: 77.2030,
  },
  { // Malka Ganj[web:429][web:432]
    id: "NORTH_MALKA_GANJ",
    name: "Malka Ganj",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6887,
    lon: 77.2137,
  },
  { // Timarpur – approximate ward centroid near Timarpur locality[web:281][web:289]
    id: "NORTH_TIMARPUR",
    name: "Timarpur",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.7090,
    lon: 77.2230,
  },
  { // Mukherji Nagar / Mukherjee Nagar[web:436][web:438][web:448]
    id: "NORTH_MUKHERJI_NAGAR",
    name: "Mukherji Nagar",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.7055,
    lon: 77.2035,
  },
  { // Kamla Nagar[web:441][web:445][web:449]
    id: "NORTH_KAMLA_NAGAR",
    name: "Kamla Nagar",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6887,
    lon: 77.2137,
  },
  { // Shastri Nagar[web:446][web:450]
    id: "NORTH_SHASTRI_NAGAR",
    name: "Shastri Nagar",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6700,
    lon: 77.1819,
  },
  { // Inderlok Colony (using Inderlok locality / metro centroid)[web:443][web:447]
    id: "NORTH_INDERLOK_COLONY",
    name: "Inderlok Colony",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6734,
    lon: 77.1703,
  },
  { // Kishan Ganj[web:372][web:452]
    id: "NORTH_KISHAN_GANJ",
    name: "Kishan Ganj",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6603,
    lon: 77.1988,
  },
  { // Deputy Ganj – approximate Old Delhi goods yard area near Kishan Ganj[web:281][web:284]
    id: "NORTH_DEPUTY_GANJ",
    name: "Deputy Ganj",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6635,
    lon: 77.2090,
  },
  { // Kashmere Gate / ISBT area[web:455][web:458][web:461]
    id: "NORTH_KASHMERE_GATE",
    name: "Kashmere Gate",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6671,
    lon: 77.2291,
  },
  { // Majnoo Ka Tilla / Majnu Ka Tilla[web:456][web:459]
    id: "NORTH_MAJNOO_KA_TILLA",
    name: "Majnoo Ka Tilla",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.7011,
    lon: 77.2280,
  },
  { // Chandni Chawk / Chandni Chowk[web:462][web:466][web:469]
    id: "NORTH_CHANDNI_CHAWK",
    name: "Chandni Chawk",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6506,
    lon: 77.2303,
  },
  { // Eidgah Road – approximate, near Idgah area in central/north Delhi[web:473][web:281]
    id: "NORTH_EIDGAH_ROAD",
    name: "Eidgah Road",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6538,
    lon: 77.2057,
  },
  { // Ram Nagar (keeping your earlier North-Delhi-side Ram Nagar; if you prefer Central, adjust district)[web:299]
    id: "NORTH_RAM_NAGAR",
    name: "Ram Nagar",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6860,
    lon: 77.2958,
  },
  { // Kasabpura, Sadar Bazar belt – approximate point near listed schools and Sadar Bazar area[web:479][web:281]
    id: "NORTH_KASABPURA",
    name: "Kasabpura",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6610,
    lon: 77.2015,
  },
  { // Model Basti, Karol Bagh side[web:477][web:478]
    id: "NORTH_MODEL_BASTI",
    name: "Model Basti",
    district: "North Delhi",
    districtId: "NORTH_DELHI",
    lat: 28.6500,
    lon: 77.2000,
  },
  { // Welcome Colony (using Welcome metro centroid for the ward)[web:487]
    id: "NORTH_EAST_WELCOME_COLONY",
    name: "Welcome Colony",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.6721,
    lon: 77.2780,
  },
  { // Seelampur[web:489][web:492][web:496]
    id: "NORTH_EAST_SEELAMPUR",
    name: "Seelampur",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.6701,
    lon: 77.2666,
  },
  { // Gautam Puri – approximate; North‑East Delhi side of Gautam Puri colony[web:475][web:284]
    id: "NORTH_EAST_GAUTAM_PURI",
    name: "Gautam Puri",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.6550,
    lon: 77.2900,
  },
  { // Chauhan Banger (Seelampur/Shahdara)[web:490][web:494]
    id: "NORTH_EAST_CHAUHAN_BANGER",
    name: "Chauhan Banger",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.6353,
    lon: 77.2250,
  },
  { // Kabir Nagar, Shahdara side[web:527][web:533]
    id: "NORTH_EAST_KABIR_NAGAR",
    name: "Kabir Nagar",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.6935,
    lon: 77.2810,
  },
  { // Gorakh Park[web:531][web:538]
    id: "NORTH_EAST_GORAKH_PARK",
    name: "Gorakh Park",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.6829,
    lon: 77.2805,
  },
  { // Kardam Puri[web:534]
    id: "NORTH_EAST_KARDAM_PURI",
    name: "Kardam Puri",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.6970,
    lon: 77.2790,
  },
  { // Harsh Vihar (Mandoli–Saboli / 110093 side)[web:540][web:547][web:550]
    id: "NORTH_EAST_HARSH_VIHAR",
    name: "Harsh Vihar",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7019,
    lon: 77.3050,
  },
  { // Saboli (Mandoli Saboli)[web:544][web:547][web:550]
    id: "NORTH_EAST_SABOLI",
    name: "Saboli",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7019,
    lon: 77.3050,
  },
  { // Gokal Puri / Gokulpuri[web:545][web:548][web:551][web:553]
    id: "NORTH_EAST_GOKAL_PURI",
    name: "Gokal Puri",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7034,
    lon: 77.2829,
  },
  { // Joharipur / Johripur[web:554][web:556][web:557]
    id: "NORTH_EAST_JOHARIPUR",
    name: "Joharipur",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7213,
    lon: 77.2746,
  },
  { // Karawal Nagar East (offset from Karawal Nagar centroid towards east)[web:559][web:563][web:567]
    id: "NORTH_EAST_KARAWAL_NAGAR_EAST",
    name: "Karawal Nagar East",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7311,
    lon: 77.2795,
  },
  { // Dayalpur[web:560][web:564][web:568]
    id: "NORTH_EAST_DAYALPUR",
    name: "Dayalpur",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7186,
    lon: 77.2614,
  },
  { // Mustafabad[web:561]
    id: "NORTH_EAST_MUSTAFABAD",
    name: "Mustafabad",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7112,
    lon: 77.2680,
  },
  { // Nehru Vihar (near Mustafabad / Dayalpur)[web:565][web:568]
    id: "NORTH_EAST_NEHRU_VIHAR",
    name: "Nehru Vihar",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7113,
    lon: 77.2676,
  },
  { // Brij Puri / Brijpuri[web:569][web:571][web:580]
    id: "NORTH_EAST_BRIJ_PURI",
    name: "Brij Puri",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.6443,
    lon: 77.2833,
  },
  { // Shri Ram Colony, Khajoori Khas side[web:576]
    id: "NORTH_EAST_SHRI_RAM_COLONY",
    name: "Shri Ram Colony",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7130,
    lon: 77.2573,
  },
  { // Sadatpur (Sadatpur Extension near Karawal Nagar)[web:574][web:577]
    id: "NORTH_EAST_SADATPUR",
    name: "Sadatpur",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7230,
    lon: 77.2628,
  },
  { // Karawal Nagar West – offset west from Karawal Nagar centroid[web:559][web:567][web:577]
    id: "NORTH_EAST_KARAWAL_NAGAR_WEST",
    name: "Karawal Nagar West",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7270,
    lon: 77.2600,
  },
  { // Sonia Vihar[web:581][web:584][web:585][web:587]
    id: "NORTH_EAST_SONIA_VIHAR",
    name: "Sonia Vihar",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7234,
    lon: 77.2608,
  },
  { // Sabapur / Sabhapur, near Sonia Vihar[web:591][web:593]
    id: "NORTH_EAST_SABAPUR",
    name: "Sabapur",
    district: "North East Delhi",
    districtId: "NORTH_EAST_DELHI",
    lat: 28.7350,
    lon: 77.2700,
  },
  { // Narela[web:597][web:600][web:601]
    id: "NORTH_WEST_NARELA",
    name: "Narela",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.8530,
    lon: 77.0910,
  },
  { // Bankner[web:602][web:606][web:610]
    id: "NORTH_WEST_BANKNER",
    name: "Bankner",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.8493,
    lon: 77.0975,
  },
  { // Alipur[web:603][web:607][web:611]
    id: "NORTH_WEST_ALIPUR",
    name: "Alipur",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.7980,
    lon: 77.1331,
  },
  { // Bakhtawarpur / Bakhtawar Pur[web:604][web:608]
    id: "NORTH_WEST_BAKHTAWARPUR",
    name: "Bakhtawarpur",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.8182,
    lon: 77.1585,
  },
  { // Bhalaswa Jahangirpuri / Bhalswa Jahangirpur area[web:613][web:616][web:618]
    id: "NORTH_WEST_BHALASWA_JAHANGIRPURI",
    name: "Bhalaswa Jahangirpuri",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.7350,
    lon: 77.1636,
  },
  { // Mukherji Nagar (North West slice; you also have it under North Delhi)[web:436][web:438][web:448]
    id: "NORTH_WEST_MUKHERJI_NAGAR",
    name: "Mukherji Nagar",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",

    lat: 28.7055,
    lon: 77.2035,
  },
  { // G.T.B. Nagar / Guru Tegh Bahadur Nagar[web:617][web:619][web:624]
    id: "NORTH_WEST_GTB_NAGAR",
    name: "G.T.B. Nagar",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.7107,
    lon: 77.1969,
  },
  { // Dhirpur – approximate near Dayalpur/Tukhmirpur belt[web:568][web:592]
    id: "NORTH_WEST_DHIRPUR",
    name: "Dhirpur",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.7250,
    lon: 77.2000,
  },
  { // Adarsh Nagar[web:625][web:629][web:632]
    id: "NORTH_WEST_ADARSH_NAGAR",
    name: "Adarsh Nagar",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.7145,
    lon: 77.1666,
  },
  { // Sarai Pepal Thalla / Sarai Pipal Thala area near Adarsh Nagar–Azadpur[web:630][web:636]
    id: "NORTH_WEST_SARAI_PEPAL_THALLA",
    name: "Sarai Pepal Thalla",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.7070,
    lon: 77.1700,
  },
  { // Jahangirpuri - I (first ward; use core Jahangirpuri centroid)[web:618][web:621]
    id: "NORTH_WEST_JAHANGIRPURI_I",
    name: "Jahangirpuri - I",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.7380,
    lon: 77.1650,
  },
  { // Samaypur Badli[web:631][web:634][web:637]
    id: "NORTH_WEST_SAMAYPUR_BADLI",
    name: "Samaypur Badli",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.7446,
    lon: 77.1383,
  },
  { // Libaspur / Libas Pur (near Samaypur)[web:640][web:641][web:643]
    id: "NORTH_WEST_LIBASPUR",
    name: "Libaspur",
    district: "North West Delhi",
    districtId: "NORTH_WEST_DELHI",
    lat: 28.7500,
    lon: 77.1465,
  },
  { // New Ashok Nagar[web:648][web:650][web:651]
    id: "SHAHDARA_NEW_ASHOK_NAGAR",
    name: "New Ashok Nagar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.5930,
    lon: 77.3052,
  },
  { // Mayur Vihar Phase-I[web:327][web:331][web:656]
    id: "SHAHDARA_MAYUR_VIHAR_PHASE_I",
    name: "Mayur Vihar Phase-I",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6044,
    lon: 77.2883,
  },
  { // Trilokpuri[web:337][web:341][web:654]
    id: "SHAHDARA_TRILOKPURI",
    name: "Trilokpuri",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6118,
    lon: 77.3145,
  },
  { // Kondli[web:348][web:658][web:660]
    id: "SHAHDARA_KONDLI",
    name: "Kondli",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6146,
    lon: 77.3261,
  },
  { // Gharoli[web:349][web:352][web:353][web:662]
    id: "SHAHDARA_GHAROLI",
    name: "Gharoli",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6170,
    lon: 77.3317,
  },
  { // Kalyanpuri[web:342][web:343][web:346]
    id: "SHAHDARA_KALYANPURI",
    name: "Kalyanpuri",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6167,
    lon: 77.3189,
  },
  { // Mayur Vihar Phase-II[web:370][web:374]
    id: "SHAHDARA_MAYUR_VIHAR_PHASE_II",
    name: "Mayur Vihar Phase-II",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6175,
    lon: 77.3066,
  },
  { // Patparganj[web:371][web:375][web:378]
    id: "SHAHDARA_PATPARGANJ",
    name: "Patparganj",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6356,
    lon: 77.3108,
  },
  { // Vinod Nagar (use East Vinod Nagar centroid here)[web:357][web:363][web:667]
    id: "SHAHDARA_VINOD_NAGAR",
    name: "Vinod Nagar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6227,
    lon: 77.3039,
  },
  { // Mandawali[web:367][web:668][web:671]
    id: "SHAHDARA_MANDAWALI",
    name: "Mandawali",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6249,
    lon: 77.3045,
  },
  { // Pandav Nagar (Shahdara side – using East Delhi centroid similar to Pandav Nagar near Akshardham)[web:674][web:675]
    id: "SHAHDARA_PANDAV_NAGAR",
    name: "Pandav Nagar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6140,
    lon: 77.2750,
  },
  { // Lalita Park (near Laxmi Nagar; approximate ward centroid within the same cluster as Ramesh Park/Lalita Park camps)[web:288]
    id: "SHAHDARA_LALITA_PARK",
    name: "Lalita Park",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6370,
    lon: 77.2720,
  },
  { // Shakarpur (adjacent to Laxmi Nagar; use standard Shakarpur coordinates in East/Shahdara belt)[web:288]
    id: "SHAHDARA_SHAKARPUR",
    name: "Shakarpur",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6375,
    lon: 77.2815,
  },
  { // Laxmi Nagar[web:288]
    id: "SHAHDARA_LAXMI_NAGAR",
    name: "Laxmi Nagar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6362,
    lon: 77.2705,
  },
  { // Preet Vihar (using Preet Vihar C‑Block/Jaina Tower centroid)[web:288]
    id: "SHAHDARA_PREET_VIHAR",
    name: "Preet Vihar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6388,
    lon: 77.2925,
  },
  { // I.P. Extension (IP Extension metro/colony area)[web:681][web:687]
    id: "SHAHDARA_IP_EXTENSION",
    name: "I.P. Extension",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6319,
    lon: 77.3109,
  },
  { // Anand Vihar (Shahdara side, near ISBT/railway station)[web:686]
    id: "SHAHDARA_ANAND_VIHAR",
    name: "Anand Vihar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6480,
    lon: 77.3150,
  },
  { // Vishwas Nagar – colony off Shahdara / Jagat Puri belt (approximate ward centroid)[web:684][web:688]
    id: "SHAHDARA_VISHWAS_NAGAR",
    name: "Vishwas Nagar",
    district: "Shahdara",
districtId: "SHAHDARA",
    lat: 28.6560,
    lon: 77.2970,
  },
  { // Anarkali (Krishna Nagar / Swasthya Vihar side commercial cluster, approximate)[web:684]
    id: "SHAHDARA_ANARKALI",
    name: "Anarkali",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6400,
    lon: 77.2900,
  },
  { // Jagat Puri (between Krishna Nagar and Karkardooma, approximate)[web:684]
    id: "SHAHDARA_JAGAT_PURI",
    name: "Jagat Puri",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6445,
    lon: 77.3015,
  },
  { // Geeta Colony (Shahdara side; centroid from locality listings)[web:689][web:691][web:693]
    id: "SHAHDARA_GEETA_COLONY",
    name: "Geeta Colony",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6621,
    lon: 77.2667,
  },
  { // Krishna Nagar (assembly seat / commercial hub; approximate ward centroid within East–Shahdara belt)[web:288][web:695]
    id: "SHAHDARA_KRISHNA_NAGAR",
    name: "Krishna Nagar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6470,
    lon: 77.2930,
  },
  { // Gandhi Nagar (cloth market / industrial‑residential mix near Geeta Colony)[web:288][web:692]
    id: "SHAHDARA_GANDHI_NAGAR",
    name: "Gandhi Nagar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6610,
    lon: 77.2780,
  },
  { // Shastri Park (Yamuna‑side locality and metro area; approximate)[web:288][web:520]
    id: "SHAHDARA_SHASTRI_PARK",
    name: "Shastri Park",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6715,
    lon: 77.2430,
  },
  { // Azad Nagar (small colony in the same trans‑Yamuna cluster; approximate ward centroid)[web:288][web:682]
    id: "SHAHDARA_AZAD_NAGAR",
    name: "Azad Nagar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6550,
    lon: 77.2830,
  },
  { // Shahdara main locality / ward centroid[web:700]
    id: "SHAHDARA_SHAHDARA",
    name: "Shahdara",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6988,
    lon: 77.2926,
  },
  { // Jhilmil (industrial/residential pocket near GT Road; approximate within Shahdara district)[web:701]
    id: "SHAHDARA_JHILMIL",
    name: "Jhilmil",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6760,
    lon: 77.3170,
  },
  { // Dilshad Colony (near Dilshad Garden; approximate centroid of the colony)[web:701]
    id: "SHAHDARA_DILSHAD_COLONY",
    name: "Dilshad Colony",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6865,
    lon: 77.3205,
  },
  { // Sundar Nagri (Nand Nagri / North‑east Shahdara belt; approximate)[web:699][web:701]
    id: "SHAHDARA_SUNDAR_NAGRI",
    name: "Sundar Nagri",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7040,
    lon: 77.3200,
  },
  { // Dilshad Garden (metro/colony centroid)[web:701]
    id: "SHAHDARA_DILSHAD_GARDEN",
    name: "Dilshad Garden",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6810,
    lon: 77.3220,
  },
  { // Nand Nagri[web:703][web:704][web:709]
    id: "SHAHDARA_NAND_NAGRI",
    name: "Nand Nagri",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7019,
    lon: 77.3080,
  },
  { // Ashok Nagar (Shahdara side, approximate within Shahdara district)[web:701]
    id: "SHAHDARA_ASHOK_NAGAR",
    name: "Ashok Nagar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6750,
    lon: 77.3100,
  },
  { // Ram Nagar East (distinct from other Ram Nagar localities; approximate in Shahdara belt)[web:288]
    id: "SHAHDARA_RAM_NAGAR_EAST",
    name: "Ram Nagar East",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6760,
    lon: 77.3000,
  },
  { // Rohtash Nagar (near Shahdara GT Road; approximate ward centroid)[web:288][web:701]
    id: "SHAHDARA_ROHTASH_NAGAR",
    name: "Rohtash Nagar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6800,
    lon: 77.2950,
  },
  { // Welcome Colony (reusing the Welcome / Seelampur cluster but tagged to Shahdara ward)[web:487]
    id: "SHAHDARA_WELCOME_COLONY",
    name: "Welcome Colony",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6721,
    lon: 77.2780,
  },
  { // Seelampur (using metro/locality centroid; same coords as earlier North‑East entry but ward in Shahdara)
    id: "SHAHDARA_SEELAMPUR",
    name: "Seelampur",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6699,  // from published Seelampur locality/metro coordinates[web:492][web:712][web:714]
    lon: 77.2666,
  },
  { // Gautam Puri – Shahdara-side Jhuggi/JJ cluster near Seelampur (kept consistent with your earlier North‑East Gautam Puri centroid)
    id: "SHAHDARA_GAUTAM_PURI",
    name: "Gautam Puri",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6550,  // approximate within the same trans‑Yamuna belt as your existing entry[web:288]
    lon: 77.2900,
  },
  { // Chauhan Banger (overlaps Seelampur/Shahdara area; reuse earlier Chauhan Banger point)
    id: "SHAHDARA_CHAUHAN_BANGER",
    name: "Chauhan Banger",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6353,  // approximate for the Shahdara‑Seelampur locality from public maps[web:490][web:494]
    lon: 77.2250,
  },
  { // Maujpur (same colony as North‑East ward, tagged under Shahdara for this ward list)
    id: "SHAHDARA_MAUJPUR",
    name: "Maujpur",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6903,  // locality centroid from Maujpur listings[web:497][web:501]
    lon: 77.2737,
  },
  { // Braham Puri / Brahampuri (road/colony near New Seelampur)
    id: "SHAHDARA_BRAHAM_PURI",
    name: "Braham Puri",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6756,  // Brahampuri coordinates reused for this spelling variant[web:502][web:505][web:511]
    lon: 77.2645,
  },
  { // Bhajanpura (Shahdara side – reuse the established Bhajanpura centroid from public sources)
    id: "SHAHDARA_BHAJANPURA",
    name: "Bhajanpura",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7005,  // typical published value around 28.700–28.703 N, 77.259–77.264 E[web:506][web:509]
    lon: 77.2592,
  },
  { // Ghonda (same Ghonda/Ghonda Chowk cluster you used in North‑East Delhi)
    id: "SHAHDARA_GHONDA",
    name: "Ghonda",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6942,  // consistent with earlier Ghonda locality coordinates[web:512][web:515]
    lon: 77.2646,
  },
  { // Yamuna Vihar (explicitly tagged to Shahdara in locality datasets)
    id: "SHAHDARA_YAMUNA_VIHAR",
    name: "Yamuna Vihar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7009,  // from Yamuna Vihar, Shahdara locality coordinates[web:520]
    lon: 77.2721,
  },
  { // Subhash Mohalla (same pocket near Bhajanpura/Yamuna Vihar as your North‑East ward)
    id: "SHAHDARA_SUBHASH_MOHALLA",
    name: "Subhash Mohalla",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6990,  // kept equal to your earlier Subhash Mohalla ward centroid in this belt[web:520]
    lon: 77.2680,
  },
  { // Gorakh Park (reusing the Shahdara/West Gorakh Park centroid)
    id: "SHAHDARA_GORAKH_PARK",
    name: "Gorakh Park",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6829,  // West Gorakh Park coordinates already used earlier[web:531][web:538]
    lon: 77.2805,
  },
  { // Kardam Puri (same cluster as earlier Kardam Puri ward)
    id: "SHAHDARA_KARDAM_PURI",
    name: "Kardam Puri",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6970,  // reused from your North East Kardam Puri entry, which matches Shahdara‑side locality data[web:534][web:683]
    lon: 77.2790,
  },
  { // Harsh Vihar (Mandoli–Saboli side)
    id: "SHAHDARA_HARSH_VIHAR",
    name: "Harsh Vihar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7019,  // consistent with the Harsh Vihar 110093 coordinates you used before[web:540][web:542]
    lon: 77.3050,
  },
  { // Saboli (Mandoli Saboli pocket)
    id: "SHAHDARA_SABOLI",
    name: "Saboli",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7019,  // same Mandoli–Saboli centroid as earlier Saboli ward[web:547][web:550]
    lon: 77.3050,
  },
  { // Joharipur / Johripur
    id: "SHAHDARA_JOHARIPUR",
    name: "Joharipur",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7213,  // reused from your North East Joharipur centroid based on Johripur locality sources[web:554][web:556]
    lon: 77.2746,
  },
  { // Karawal Nagar East
    id: "SHAHDARA_KARAWAL_NAGAR_EAST",
    name: "Karawal Nagar East",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7311,  // same east‑offset Karawal Nagar point you already defined[web:559][web:563]
    lon: 77.2795,
  },
  { // Dayalpur – reuse the same centroid you used for the North East Delhi ward
    id: "SHAHDARA_DAYALPUR",
    name: "Dayalpur",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7186,  // from Dayalpur, Tukhmirpur locality coordinates[web:568]
    lon: 77.2614,
  },
  { // Mustafabad – same locality centroid as your North East Delhi Mustafabad ward
    id: "SHAHDARA_MUSTAFABAD",
    name: "Mustafabad",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7112,  // Mustafabad, Delhi coordinates[web:561]
    lon: 77.2680,
  },
  { // Nehru Vihar – near Mustafabad/Dayalpur cluster
    id: "SHAHDARA_NEHRU_VIHAR",
    name: "Nehru Vihar",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7113,  // same as earlier Nehru Vihar ward centroid[web:565]
    lon: 77.2676,
  },
  { // Brij Puri – same Brijpuri centroid you used under North East Delhi
    id: "SHAHDARA_BRIJ_PURI",
    name: "Brij Puri",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.6443,  // Brijpuri locality coordinates[web:569][web:571]
    lon: 77.2833,
  },
  { // Shri Ram Colony – Khajoori Khas pushta‑side colony
    id: "SHAHDARA_SHRI_RAM_COLONY",
    name: "Shri Ram Colony",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7130,  // from Shriram Colony, Khajoori Khas locality data[web:576]
    lon: 77.2573,
  },
  { // Sadatpur – same centroid as earlier North East Sadatpur/Sadatpur Extension ward[web:731][web:732]
    id: "SHAHDARA_SADATPUR",
    name: "Sadatpur",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7224,
    lon: 77.2629,
  },
  { // Karawal Nagar West – reuse your existing west‑offset Karawal Nagar point[web:734]
    id: "SHAHDARA_KARAWAL_NAGAR_WEST",
    name: "Karawal Nagar West",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7270,
    lon: 77.2600,
  },
  { // Sabapur / Sabhapur – same coordinates as your North East Sabapur ward[web:591][web:593]
    id: "SHAHDARA_SABAPUR",
    name: "Sabapur",
    district: "Shahdara",
    districtId: "SHAHDARA",
    lat: 28.7350,
    lon: 77.2700,
  },
  { // Kalkaji – central point in the Kalkaji temple/colony area
    id: "SOUTH_EAST_KALKAJI",
    name: "Kalkaji",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5480,  // approx within Kalkaji, in South East Delhi district[web:741]
    lon: 77.2590,
  },
  { // Govind Puri
    id: "SOUTH_EAST_GOVIND_PURI",
    name: "Govind Puri",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5354,  // Govindpuri coordinates in South East Delhi[web:735][web:740]
    lon: 77.2639,
  },
  { // Harkesh Nagar – near Okhla industrial area
    id: "SOUTH_EAST_HARKESH_NAGAR",
    name: "Harkesh Nagar",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5490,  // approximate centroid in the Okhla/Harkesh Nagar pocket[web:741]
    lon: 77.2760,
  },
  { // Tughlakabad (historic fort / residential belt)
    id: "SOUTH_EAST_TUGHLAKABAD",
    name: "Tughlakabad",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5150,  // within the Tughlakabad ridge area south of Kalkaji[web:488][web:741]
    lon: 77.2680,
  },
  { // Tughlakabad Extension – immediately east of main Tughlakabad colony
    id: "SOUTH_EAST_TUGHLAKABAD_EXTENSION",
    name: "Tughlakabad Extension",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5180,  // small eastward offset from Tughlakabad point[web:488][web:741]
    lon: 77.2760,
  },
  { // Pul Pehladpur / Pul Prahlad Pur – census town in South East Delhi[web:743][web:747][web:748]
    id: "SOUTH_EAST_PUL_PEHLADPUR",
    name: "Pul Pehladpur",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.4980,
    lon: 77.2940,
  },
  { // Badarpur – near Delhi–Haryana border, South East Delhi side[web:741]
    id: "SOUTH_EAST_BADARPUR",
    name: "Badarpur",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.4970,
    lon: 77.3030,
  },
  { // Molarband – residential area south of Badarpur (approximate centroid in same belt)[web:741]
    id: "SOUTH_EAST_MOLARBAND",
    name: "Molarband",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.4880,
    lon: 77.3020,
  },
  { // Meethapur – near Kalindi Kunj / Delhi–Noida border in South East Delhi[web:741]
    id: "SOUTH_EAST_MEETHAPUR",
    name: "Meethapur",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.4810,
    lon: 77.3140,
  },
  { // Jaitpur – village/urban village on Yamuna side in South East Delhi[web:741]
    id: "SOUTH_EAST_JAITPUR",
    name: "Jaitpur",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5060,
    lon: 77.3190,
  },
  { // Hari Nagar Extension – colony in the same South East Delhi corridor (approximate)[web:741]
    id: "SOUTH_EAST_HARI_NAGAR_EXTENSION",
    name: "Hari Nagar Extension",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5130,
    lon: 77.2980,
  },
  { // Madanpur Khadar East – JJ Colony side around 28.5301 N, 77.3137 E[web:757]
    id: "SOUTH_EAST_MADANPUR_KHADAR_EAST",
    name: "Madanpur Khadar East",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5301,
    lon: 77.3137,
  },
  { // Madanpur Khadar West – village core around 28.534–28.535 N, 77.30 E[web:751][web:752]
    id: "SOUTH_EAST_MADANPUR_KHADAR_WEST",
    name: "Madanpur Khadar West",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5345,
    lon: 77.2993,
  },
  { // Sarita Vihar – nearby planned residential pocket[web:754][web:755]
    id: "SOUTH_EAST_SARITA_VIHAR",
    name: "Sarita Vihar",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5370,
    lon: 77.3000,
  },
  { // Abul Fazal Enclave – Jamia Nagar side (Okhla)[web:741]
    id: "SOUTH_EAST_ABUL_FAZAL_ENCLAVE",
    name: "Abul Fazal Enclave",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5550,
    lon: 77.3000,
  },
  { // Zakir Nagar – Jamia Nagar / Okhla pocket in South East Delhi[web:761][web:762][web:764][web:768]
    id: "SOUTH_EAST_ZAKIR_NAGAR",
    name: "Zakir Nagar",
    district: "South East Delhi",
    districtId: "SOUTH_EAST_DELHI",
    lat: 28.5672,
    lon: 77.2790,
  },
  { // Dabri – in South West Delhi near Janakpuri[web:775][web:774]
    id: "SOUTH_WEST_DABRI",
    name: "Dabri",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.6160,
    lon: 77.0690,
  },
  { // Sagarpur – West/South West Delhi belt near Dabri[web:775][web:774]
    id: "SOUTH_WEST_SAGARPUR",
    name: "Sagarpur",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.6230,
    lon: 77.0790,
  },
  { // Manglapuri – close to Palam in South West Delhi[web:772][web:774]
    id: "SOUTH_WEST_MANGLAPURI",
    name: "Manglapuri",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5950,
    lon: 77.0800,
  },
  { // Dwarka-B – western part of Dwarka sub‑division[web:772][web:776]
    id: "SOUTH_WEST_DWARKA_B",
    name: "Dwarka-B",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5880,
    lon: 77.0260,
  },
  { // Dwarka-A – eastern/central Dwarka sector cluster[web:772][web:776]
    id: "SOUTH_WEST_DWARKA_A",
    name: "Dwarka-A",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5940,
    lon: 77.0450,
  },
  { // Matiala – assembly segment listed under South West Delhi[web:775][web:772]
    id: "SOUTH_WEST_MATIALA",
    name: "Matiala",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.6130,
    lon: 77.0300,
  },

  { // Kakrola – locality between Dwarka and Najafgarh[web:782][web:785]
    id: "SOUTH_WEST_KAKROLA",
    name: "Kakrola",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.6060,
    lon: 77.0100,
  },
  { // Nangli Sakrawati – village near Najafgarh (approximate centroid in same rural belt)[web:784]
    id: "SOUTH_WEST_NANGLI_SAKRAWATI",
    name: "Nangli Sakrawati",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5960,
    lon: 76.9900,
  },
  { // Chhawla – village in Najafgarh tehsil[web:786][web:789][web:792]
    id: "SOUTH_WEST_CHHAWLA",
    name: "Chhawla",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5621,
    lon: 77.0023,
  },
  { // Isapur / Issapur – rural locality in far South West Delhi[web:784]
    id: "SOUTH_WEST_ISAPUR",
    name: "Isapur",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5850,
    lon: 76.8830,
  },
  { // Najafgarh – major town in South West Delhi[web:470][web:787]
    id: "SOUTH_WEST_NAJAFGARH",
    name: "Najafgarh",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.6090,
    lon: 76.9855,
  },
  { // Dichaon Kalan – village near Najafgarh (approximate centroid from local listings)[web:784]
    id: "SOUTH_WEST_DICHAON_KALAN",
    name: "Dichaon Kalan",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.6260,
    lon: 76.9500,
  },
  { // Roshan Pura / New Roshanpura (Dichaon Khurd side near Najafgarh)[web:793][web:802][web:805]
    id: "SOUTH_WEST_ROSHAN_PURA",
    name: "Roshan Pura",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5998,
    lon: 76.9868,
  },
  { // Dwarka-C – third Dwarka ward; place it slightly south of Dwarka-A/B cluster[web:772][web:774]
    id: "SOUTH_WEST_DWARKA_C",
    name: "Dwarka-C",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5800,
    lon: 77.0400,
  },
  { // Bijwasan[web:797][web:800][web:803][web:806]
    id: "SOUTH_WEST_BIJWASAN",
    name: "Bijwasan",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5350,
    lon: 77.0530,
  },
  { // Kapashera[web:798][web:801][web:804]
    id: "SOUTH_WEST_KAPASHERA",
    name: "Kapashera",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5273,
    lon: 77.0823,
  },
  { // Mahipalpur – near airport, adjacent to Kapashera side[web:772][web:774]
    id: "SOUTH_WEST_MAHIPALPUR",
    name: "Mahipalpur",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5440,
    lon: 77.1240,
  },
  { // Raj Nagar (Palam/Raj Nagar Part‑II belt; approximate centroid in South West Delhi)[web:772][web:774]
    id: "SOUTH_WEST_RAJ_NAGAR",
    name: "Raj Nagar",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5860,
    lon: 77.0710,
  },
  { // Palam – village/colony in South West Delhi[web:811][web:814][web:820]
    id: "SOUTH_WEST_PALAM",
    name: "Palam",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5612,
    lon: 77.1218,
  },
  { // Madhu Vihar – Dwarka‑side sublocality around Sector 3/6[web:813][web:819]
    id: "SOUTH_WEST_MADHU_VIHAR",
    name: "Madhu Vihar",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.6080,
    lon: 77.0580,
  },
  { // Mahavir Enclave – Palam–Dabri Marg side[web:812][web:815][web:818]
    id: "SOUTH_WEST_MAHAVIR_ENCLAVE",
    name: "Mahavir Enclave",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5970,
    lon: 77.0812,
  },
  { // Sadh Nagar – near Palam in the same corridor (approximate centroid)[web:811][web:820]
    id: "SOUTH_WEST_SADH_NAGAR",
    name: "Sadh Nagar",
    district: "South West Delhi",
    districtId: "SOUTH_WEST_DELHI",
    lat: 28.5650,
    lon: 77.1100,
  },
  { // Punjabi Bagh – subdivision HQ of West Delhi, also an MCD ward in West Zone[web:822][web:824][web:826]
    id: "WEST_PUNJABI_BAGH",
    name: "Punjabi Bagh",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6710,
    lon: 77.1290,
  },
  { // Madipur – MCD ward 93 in West Zone, adjacent to Punjabi Bagh[web:826]
    id: "WEST_MADIPUR",
    name: "Madipur",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6690,
    lon: 77.1200,
  },
  { // Raghubir Nagar – MCD ward 94 in West Zone, near Rajouri Garden[web:826]
    id: "WEST_RAGHUBIR_NAGAR",
    name: "Raghubir Nagar",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6615,
    lon: 77.1105,
  },
  { // Vishnu Garden – MCD ward 95 in West Zone[web:826]
    id: "WEST_VISHNU_GARDEN",
    name: "Vishnu Garden",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6505,
    lon: 77.0885,
  },
  { // Rajouri Garden – subdivision HQ and MCD ward 96 in West Zone[web:822][web:824][web:826]
    id: "WEST_RAJOURI_GARDEN",
    name: "Rajouri Garden",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6425,
    lon: 77.1230,
  },
  { // Chaukhandi Nagar / Chaukhandi – locality under Tilak Nagar, West Delhi[web:831][web:832][web:835]
    id: "WEST_CHAUKHANDI_NAGAR",
    name: "Chaukhandi Nagar",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6446,
    lon: 77.0953,
  },
  { // Subhash Nagar – historic neighbourhood near Rajouri/Tagore Garden in West Delhi[web:837]
    id: "WEST_SUBHASH_NAGAR",
    name: "Subhash Nagar",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6415,
    lon: 77.0905,
  },
  { // Hari Nagar – residential locality along Mayapuri Road in West Delhi[web:841][web:843]
    id: "WEST_HARI_NAGAR",
    name: "Hari Nagar",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6295,
    lon: 77.0955,
  },
  { // Fateh Nagar – locality adjoining Hari Nagar/Janakpuri–Rajouri belt in West Delhi[web:839]
    id: "WEST_FATEH_NAGAR",
    name: "Fateh Nagar",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6290,
    lon: 77.0860,
  },
  { // Tilak Nagar – major residential/commercial locality and ward in West Delhi[web:836][web:840][web:842]
    id: "WEST_TILAK_NAGAR",
    name: "Tilak Nagar",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6365,
    lon: 77.0775,
  },
  { // Khyala (Khayala) – locality in West Delhi near Vishnu Garden[web:846][web:852][web:855][web:858]
    id: "WEST_KHYALA",
    name: "Khyala",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6551,
    lon: 77.1010,
  },
  { // Keshopur – locality within Vikaspuri area of West Delhi[web:850][web:856][web:859]
    id: "WEST_KESHOPUR",
    name: "Keshopur",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6477,
    lon: 77.0823,
  },
  { // Janak Puri South – southern part of Janakpuri; place slightly south of Janakpuri centroid[web:851][web:854][web:857]
    id: "WEST_JANAKPURI_SOUTH",
    name: "Janak Puri South",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6120,
    lon: 77.0880,
  },
  { // Mahaveer Enclave – West Delhi spelling variant, but functionally same urban belt as Mahavir Enclave; keep coordinates close to earlier point[web:812][web:815][web:818]
    id: "WEST_MAHAVEER_ENCLAVE",
    name: "Mahaveer Enclave",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.5965,
    lon: 77.0820,
  },
  { // Janak Puri West – western side of Janakpuri; place slightly west of Janakpuri centroid toward Vikaspuri[web:851][web:854][web:857]
    id: "WEST_JANAKPURI_WEST",
    name: "Janak Puri West",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6200,
    lon: 77.0800,
  },
  { // Vikas Puri / Vikaspuri – major residential locality in West Delhi[web:861][web:862][web:864]
    id: "WEST_VIKAS_PURI",
    name: "Vikas Puri",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6388,
    lon: 77.0738,
  },
  { // Hastsal – locality near Uttam Nagar–Vikaspuri belt in West Delhi[web:868][web:874]
    id: "WEST_HASTSAL",
    name: "Hastsal",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6380,
    lon: 77.0380,
  },
  { // Vikas Nagar – colony in Uttam Nagar/Ranhola side, administratively treated with West/South‑West fringe[web:868]
    id: "WEST_VIKAS_NAGAR",
    name: "Vikas Nagar",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6420,
    lon: 77.0300,
  },
  { // Kunwar Singh Nagar – residential pocket near Nangloi–Ranhola fringe, usually mapped with West Delhi urban villages[web:868]
    id: "WEST_KUNWAR_SINGH_NAGAR",
    name: "Kunwar Singh Nagar",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6540,
    lon: 77.0300,
  },
  { // Baprola – village on the western fringe; often listed under South West but part of same Najafgarh–West belt[web:866][web:872]
    id: "WEST_BAPROLA",
    name: "Baprola",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6417,
    lon: 77.0125,
  },
  { // Sainik Enclave – residential pocket near Mohan Garden / Uttam Nagar belt in West Delhi[web:878][web:879]
    id: "WEST_SAINIK_ENCLAVE",
    name: "Sainik Enclave",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6410,
    lon: 77.0400,
  },
  { // Mohan Garden – locality close to Nawada metro, part of Uttam Nagar area in West Delhi[web:878][web:879]
    id: "WEST_MOHAN_GARDEN",
    name: "Mohan Garden",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6416,
    lon: 77.0466,
  },
  { // Nawada – neighbourhood around Nawada metro station on Najafgarh Road in West Delhi[web:880][web:883][web:886]
    id: "WEST_NAWADA",
    name: "Nawada",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6203,
    lon: 77.0451,
  },
  { // Uttam Nagar – major residential suburb in West Delhi[web:875][web:876][web:882]
    id: "WEST_UTTAM_NAGAR",
    name: "Uttam Nagar",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6369,
    lon: 77.0528,
  },
  { // Binda Pur / Bindapur – locality near Matiala–Uttam Nagar in West Delhi[web:881][web:884][web:887]
    id: "WEST_BINDA_PUR",
    name: "Binda Pur",
    district: "West Delhi",
    districtId: "WEST_DELHI",
    lat: 28.6107,
    lon: 77.0660,
  },

]

 




  

 